<a href="https://colab.research.google.com/github/Dovila-hub/Dovila-hub/blob/main/PROJETFOOT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# **IMPORTATION DE DONNÉES**

Nous utilisons pd.read pour lire les differents données qui ont deja été donné.

In [ ]:
clubs = pd.read_csv("clubs_fr.csv")
player_appearance = pd.read_csv("player_appearance.csv")
player_val_before = pd.read_csv("player_valuation_before_season.csv")
game_events = pd.read_csv("game_events.csv")
game_lineup = pd.read_csv("game_lineups.csv" , low_memory = False) #Detecte mieux le type  de données car le fichier est de grande memoire
match_2023 = pd.read_csv("match_2023.csv")
match_2013_2022 = pd.read_csv("matchs_2013_2022.csv")

# **VISUALISATION DE DONNÉES**

Nous allons afficher les 5 premiers éléments de chaque donnée pour avoir une vue de la structure des fichiers.

In [ ]:
clubs.head()

,club_id,club_code,name,domestic_competition_id,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name
0,969,montpellier-hsc,Montpellier Hérault Sport Club,FR1,25,25.7,12,48.0,8,Stade de la Mosson,32939,+€28.60m,NaN
1,1082,losc-lille,Lille Olympique Sporting Club Lille Métropole,FR1,25,25.4,18,72.0,7,Decathlon Arena-Stade Pierre-Mauroy,50186,+€3.65m,NaN
2,1160,nimes-olympique,Nîmes Olympique,FR1,26,25.4,12,46.2,3,Stade des Antonins,8033,+€2.50m,NaN
3,3911,stade-brest-29,Stade brestois 29,FR1,24,26.0,6,25.0,3,Stade Francis-Le Blé,15220,+€5.10m,NaN
4,595,sc-bastia,SC Bastia,FR1,25,27.6,8,32.0,6,Stade Armand-Cesari,16480,+€480k,NaN

In [ ]:
clubs.columns

Index(['club_id', 'club_code', 'name', 'domestic_competition_id', 'squad_size',
       'average_age', 'foreigners_number', 'foreigners_percentage',
       'national_team_players', 'stadium_name', 'stadium_seats',
       'net_transfer_record', 'coach_name'],
      dtype='object')

In [ ]:
game_events.head()

,Unnamed: 0,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id
0,6816,5d2b67957aaae6cf2a41e70cb5d4024f,2012-09-22,2223841,73,Substitutions,3911,5399,", Not reported",37516.0,NaN
1,6817,cd511880b945623db06ace57349e45b2,2012-09-22,2223841,76,Goals,3911,24459,", Penalty, 2. Goal of the Season Assist: , Fou...",NaN,24459.0
2,6818,8ca118538b45a24643ab1c9f76e50f6d,2012-09-22,2223841,56,Substitutions,3911,25113,", Not reported",22053.0,NaN
3,6819,aca68dc250aa9a3758fb2243ee679d9d,2012-09-22,2223841,88,Cards,1423,27490,1. Yellow card,NaN,NaN
4,6820,a133e4d7cdccb930f2dc7b4935754a30,2012-09-22,2223841,4,Cards,1423,43960,1. Yellow card,NaN,NaN

In [ ]:
game_events.columns

Index(['Unnamed: 0', 'game_event_id', 'date', 'game_id', 'minute', 'type',
       'club_id', 'player_id', 'description', 'player_in_id',
       'player_assist_id'],
      dtype='object')

In [ ]:
game_lineup.head()

,Unnamed: 0,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,34475,be6532aeff4c40b06e6e0da142da7dd8,2013-08-24,2330825,4811,969,Hilton,starting_lineup,Centre-Back,4,1
1,34476,4b10516c5bf9b2dfac0435c7c2bbf872,2013-08-24,2330825,5303,969,Souleymane Camara,starting_lineup,Left Winger,19,0
2,34477,46552e9ff9777efa2e2d0df3a8147d87,2013-08-24,2330825,5614,750,Cédric Kanté,starting_lineup,Centre-Back,6,1
3,34478,9c10d07e15ca9a537576aa4c04511562,2013-08-24,2330825,5686,969,Laurent Pionnier,starting_lineup,Goalkeeper,1,0
4,34479,d6592bfd4c2c2f06a388086f8b0b714e,2013-08-24,2330825,17693,750,Sébastien Roudet,starting_lineup,Left Winger,18,0

In [ ]:
game_lineup.columns

Index(['Unnamed: 0', 'game_lineups_id', 'date', 'game_id', 'player_id',
       'club_id', 'player_name', 'type', 'position', 'number', 'team_captain'],
      dtype='object')

In [ ]:
match_2023.head()

,game_id,date,home_club_id,away_club_id,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_name,away_club_name,competition_type
0,4094596,2023-08-26,583,826,Luis Enrique,Franck Haise,Parc des Princes,47000.0,François Letexier,Paris Saint-Germain Football Club,Racing Club de Lens,domestic_league
1,4094622,2023-09-16,826,347,Franck Haise,László Bölöni,Stade Bollaert-Delelis,37988.0,Stéphanie Frappart,Racing Club de Lens,Football Club de Metz,domestic_league
2,4094630,2023-09-24,969,273,Michel Der Zakarian,Bruno Génésio,Stade de la Mosson,15430.0,Stéphanie Frappart,Montpellier Hérault Sport Club,Stade Rennais Football Club,domestic_league
3,4094647,2023-10-07,347,417,László Bölöni,Francesco Farioli,Stade Saint-Symphorien,23160.0,Jérôme Brisard,Football Club de Metz,Olympique Gymnaste Club Nice Côte d'Azur,domestic_league
4,4094696,2023-12-03,244,273,Gennaro Gattuso,Julien Stéphan,Orange Vélodrome,54162.0,Willy Delajod,Olympique de Marseille,Stade Rennais Football Club,domestic_league

In [ ]:
match_2023.columns

Index(['game_id', 'date', 'home_club_id', 'away_club_id',
       'home_club_manager_name', 'away_club_manager_name', 'stadium',
       'attendance', 'referee', 'home_club_name', 'away_club_name',
       'competition_type'],
      dtype='object')

In [ ]:
match_2013_2022.head()

,Unnamed: 0,game_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type,results
0,12,2330874,2013,8. Matchday,2013-09-28,618,595,2,2,6.0,...,Stade Geoffroy-Guichard,31952.0,Antony Gautier,4-3-3 Attacking,4-2-3-1,AS Saint-Étienne,SC Bastia,2:2,domestic_league,0
1,13,2330880,2013,10. Matchday,2013-10-19,14171,855,1,2,16.0,...,Parc des Sports d’Annecy,8620.0,Philippe Kalt,4-4-2 double 6,4-4-2 double 6,Thonon Évian Grand Genève FC,EA Guingamp,1:2,domestic_league,-1
2,14,2330916,2013,15. Matchday,2013-11-30,1423,1082,0,1,18.0,...,Stade du Hainaut,14874.0,Bartolomeu Varela,4-4-2 double 6,4-3-1-2,Valenciennes FC,Lille Olympique Sporting Club Lille Métropole,0:1,domestic_league,-1
3,15,2331018,2013,21. Matchday,2014-01-18,273,14171,0,0,15.0,...,Roazhon Park,13391.0,Benoît Millot,4-3-3 Attacking,4-2-3-1,Stade Rennais Football Club,Thonon Évian Grand Genève FC,0:0,domestic_league,0
4,16,2331034,2013,24. Matchday,2014-02-08,1147,273,3,1,20.0,...,Stade François-Coty,5981.0,Benoît Bastien,4-1-4-1,4-3-3 Defending,AC Ajaccio,Stade Rennais Football Club,3:1,domestic_league,1

In [ ]:
match_2013_2022.columns

Index(['Unnamed: 0', 'game_id', 'season', 'round', 'date', 'home_club_id',
       'away_club_id', 'home_club_goals', 'away_club_goals',
       'home_club_position', 'away_club_position', 'home_club_manager_name',
       'away_club_manager_name', 'stadium', 'attendance', 'referee',
       'home_club_formation', 'away_club_formation', 'home_club_name',
       'away_club_name', 'aggregate', 'competition_type', 'results'],
      dtype='object')

In [ ]:
player_appearance.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2229837_108830,2229837,108830,415,3205,2012-08-10,Aymen Abdennour,FR1,1,0,0,0,90
1,2229837_113707,2229837,113707,969,1082,2012-08-10,Rémy Cabella,FR1,1,0,0,0,42
2,2229837_126767,2229837,126767,415,3205,2012-08-10,Ali Ahamada,FR1,0,0,0,0,90
3,2229837_126796,2229837,126796,415,60949,2012-08-10,Adrien Regattin,FR1,0,1,0,0,11
4,2229837_127032,2229837,127032,415,141,2012-08-10,Serge Aurier,FR1,0,1,0,1,84

In [ ]:
player_appearance.columns

Index(['appearance_id', 'game_id', 'player_id', 'player_club_id',
       'player_current_club_id', 'date', 'player_name', 'competition_id',
       'yellow_cards', 'red_cards', 'goals', 'assists', 'minutes_played'],
      dtype='object')

In [ ]:
player_val_before.head()

,player_id,date,market_value_in_eur,current_club_id,player_club_domestic_competition_id
0,773,2004-10-04,3500000,14171,FR1
1,1327,2004-10-04,4000000,1159,FR1
2,1423,2004-10-04,1000000,855,FR1
3,1572,2004-10-04,1000000,162,FR1
4,1613,2004-10-04,200000,855,FR1

In [ ]:
player_val_before.columns

Index(['player_id', 'date', 'market_value_in_eur', 'current_club_id',
       'player_club_domestic_competition_id'],
      dtype='object')

# **NETTOYAGE DE DONNÉES**

L’analyse des structures des fichiers CSV nous a permis d’identifier plusieurs colonnes non pertinentes pour la prédiction des résultats de match.

In [ ]:
game_events = game_events.drop(columns =['game_event_id','Unnamed: 0'] )

In [ ]:
game_lineup = game_lineup.drop(columns = ['game_lineups_id','Unnamed: 0', 'player_name'])

In [ ]:
match_2023 = match_2023.drop(columns= ['stadium','attendance'])

In [ ]:
match_2013_2022 = match_2013_2022.drop(columns= ['stadium','Unnamed: 0'])

# **EXPLORATION DE DONNÉES ET STATISTIQUES ASSOCIÉES**

Dans cette section, nous presentons une étude statistique qui permets de mieux comprendre la pertinence des variables retenues pour la prediction des resultats du match.

L'objectif est d'appuyer le choix des données lectionnées travers l'analyse des tendances clés observées dans le jeu.

Elle permet a la fin de visualiser:


*   Le nombre de victoires à domicile et à l'exterieur par équipe.
*   La moyenne de buts marqués par équipe selon le type de match.

*   La comparaison globale des performances des clubs.
*   Le nombre total de buts marqués par club.
*   Les dix meilleurs buteurs.


*   Les entraineurs les plus performants selon le nombre de victoire accumulé.

**NOMBRE DE VICTOIRES À DOMICILE / EXTERIEUR PAR ÉQUIPE**

Les performances des équipes selon le lieu du match sont un critère majeur pour prédire les résultats.

Ce code calcule le nombre de victoires à domicile et à l’extérieur pour chaque club, regroupe les résultats dans un DataFrame unique, puis génère un graphique à barres horizontales.
***Les barres bleues***  représentent ***les victoires à domicile***, tandis que ***les barres orange*** illustrent ***les victoires à l’extérieur.***

In [ ]:
# Victoire a domicile
home_wins = match_2013_2022.loc[match_2013_2022['home_club_goals'] > match_2013_2022['away_club_goals']].groupby('home_club_name')['results'].count().reset_index(name='home_wins')
# Victoire a l'exterieur
away_wins = match_2013_2022.loc[match_2013_2022['away_club_goals'] > match_2013_2022['home_club_goals']].groupby('away_club_name')['results'].count().reset_index(name='away_wins')

In [ ]:
home_wins = home_wins.rename(columns = {'home_club_name':'club_name'})
away_wins = away_wins.rename(columns = {'away_club_name':'club_name'})

Fusion des differents dataframes

In [ ]:
club_wins = home_wins.merge(away_wins, on = 'club_name' , how = 'outer').fillna(0)
club_wins['total_wins'] = club_wins['home_wins'] + club_wins['away_wins']